### ISSUE TITLE
Error when trying to local save the PDF

### ISSUE THREAD

**Issue by philipriddell** [joshcase/code-blue-auto-imaging#1]
Getting an error which I cannot currently fix: 

I am now at milestone 1.  I could generate the PDF in the browser, but when trying to generate the file as an output I generate the following error:

"Warning: file_put_contents(request.pdf): failed to open stream: Permission denied in /Applications/XAMPP/xamppfiles/htdocs/autoimaging/vendor/setasign/fpdf/fpdf.php on line 1021

Fatal error: Uncaught Exception: FPDF error: Unable to create output file: request.pdf in /Applications/XAMPP/xamppfiles/htdocs/autoimaging/vendor/setasign/fpdf/fpdf.php:271 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/autoimaging/vendor/setasign/fpdf/fpdf.php(1022): FPDF->Error('Unable to creat...') #1 /Applications/XAMPP/xamppfiles/htdocs/autoimaging/functions.php(58): FPDF->Output('F', 'request.pdf') #2 /Applications/XAMPP/xamppfiles/htdocs/autoimaging/request.php(5): generaterequest(Array) #3 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/autoimaging/vendor/setasign/fpdf/fpdf.php on line 271"

My function.php is as follows:
`<?php 

	require_once('vendor/autoload.php');

	use PHPMailer\PHPMailer\PHPMailer;
	use PHPMailer\PHPMailer\SMTP;
	use PHPMailer\PHPMailer\Exception;
	use setasign\Fpdi\Fpdi;

	function generaterequest ($array) {
		$request = new Fpdi();

		$request->AddPage();
		$request->setSourceFile('imaging_template.pdf');
		$importedPage = $request->importPage(1);
		$request->useTemplate($importedPage, 1, 1, 210);

		$request->SetFont('Helvetica');
		$request->SetTextColor(0,0,0);

		$request->SetXY(125,18);
		$request->Write(0, $array['id']);

		$request->SetXY(125,24);
		$request->Write(0, $array['last_name']);

		$request->SetXY(125,31);
		$request->Write(0, $array['first_name']);

		$request->SetXY(125,45);
		$request->Write(0, $array['date_of_birth']);

		$request->SetXY(19,55);
		$request->Write(0, $array['location']);

		$request->SetXY(20,72);
		$request->Write(0, $array['reason_for_imaging']);

		$request->SetXY(20,132);
		$request->Write(0, $array['clinical_details']);

		$request->SetXY(20,222);
		$request->Write(0, 'Phil Riddell');

		$request->SetXY(20,232);
		$request->Write(0, '1234567A');

		$request->SetXY(74,222);
		$request->Write(0, 'Doctor');

		$request->SetXY(74,232);
		$request->Write(0, '4321');

		$request->SetXY(168,222);
		$request->Write(0, date('j/n/Y'));

		$filename = 'request.pdf';
		$request->output('F', $filename);

		return $filename;

	}

	function sendrequestemail () {

	}

?>`

From what I can tell, the error seems to be suggesting that 'f' is trying to overwrite the fpdf.php file?.  

If I change `$request->output('F', $filename);` 

to 

`$request->output('D', $filename); `

the program will then generate the PDF and save it to my mac downloads folder. 

Any suggestions?

**Comment by philipriddell** [comment]
Fixed it! 

'$request->output('D', '$filename');'

**Comment by philipriddell** [comment]
Fixed it! 

`	$filename = 'request.pdf';
	$request->output('F', '$filename');`

Interesting that is will allow you to output to the browser or a generic download folder without  `'$filename'`

**Comment by joshcase** [comment]
The error you're getting - `failed to open stream: Permission denied` - normally occurs when either the folder you're trying to save the output to doesn't exist, or there are some settings in your XAMPP configuration that need changing to allow you to read and write files.

The other possibility is that you have the `request.pdf` file open in another application somewhere (likely either Preview or Adobe Acrobat Reader) and the operating system is therefore not letting your script overwrite the file. Close Adobe/Preview to fix this.

> Fixed it!
> 
> ` $filename = 'request.pdf'; $request->output('F', '$filename');`

This solution is a little bit unusual to me. It has not addressed either of the above issues. You've also put a variable inside a set of inverted commas here, essentially turning it from a variable into a string now. If this works, what is the filename of the pdf? With this solution, I expect the filename of the PDF to be `$filename` and NOT `request.pdf`. Is this the case?

If this works, it's likely that you've got `request.pdf` open in another window, because I can't think of any other situations where `$request->output('F', '$filename');` would work, whereas `$request->output('F', $filename);` wouldn't.

> 
> Interesting that is will allow you to output to the browser or a generic download folder without `'$filename'`

The downloads folder already likely has read and write permissions set for the browser.

**Comment by philipriddell** [comment]
In delayed answer to the above: 

The output of the file after my alterations was `request.pdf`.  I completely agree with what you are saying though. 

I wonder if this error is related to some of the other errors I have generated that say something like:

`mkdir(): Permission denied in...`

I have been reading those error messages as implying I don't have administrator rights, whereas I should have those rights as I am working from my own username on my Mac.

When digging further, one solution suggested was to modify the apache server settings by opening XAMPP > select Apache Web Server > Configure > Open Conf File.   In this document, I changed user from `daemon` to `'myownusername` and restarted the server.  All of the errors thrown indicating that I do not have admin access have since stopped...

Of course `'myownusername` is in place of my actual username for my mac...

**Comment by joshcase** [comment]
Brilliant work Phil. This was the exact fix I was referencing in my previous comment.

Being able to find the fixes to issues like this is actually the most important skill of all when it comes to software development in my opinion, and it looks like you’re developing that muscle nicely.

Keep up the good work!

**Comment by DantonCorbel** [comment]
I too was unable to save the pdf.

This is the error I got:

```
[30-Dec-2022 09:36:39 Europe/Berlin] PHP Fatal error:  Uncaught Exception: FPDF error: Unable to create output file: request.pdf in /Applications/XAMPP/xamppfiles/htdocs/Auto-imaging/vendor/setasign/fpdf/fpdf.php:273
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/Auto-imaging/vendor/setasign/fpdf/fpdf.php(1026): FPDF->Error('Unable to creat...')
#1 /Applications/XAMPP/xamppfiles/htdocs/Auto-imaging/functions.php(61): FPDF->Output('F', 'request.pdf')
#2 /Applications/XAMPP/xamppfiles/htdocs/auto-imaging/request.php(6): generateTheRequest(Array)
#3 {main}
  thrown in /Applications/XAMPP/xamppfiles/htdocs/Auto-imaging/vendor/setasign/fpdf/fpdf.php on line 273
```
For me it was a folder permissions issue. I changed permission for `everyone` to `read and write` and it worked. Took all day to work out that was all I needed to do.

What confused me and sent me googling in the wrong direction, though, was that if I copy-pasted @joshcase milestone1 code, the blank page loaded, but the `request.pdf` file was created somewhere else, it certainly was not where it was meant to be. I tried changing my function names in case it was calling functions from the original code but that didn't change what was happening. I even did a check to see what changes there might have been between the two pieces of code - mine and Josh's, and there was nothing different.

Anyway, changed the folder permissions, put my own code back, which was in the end not the problem, and can now finally forge on ahead...

**Comment by joshcase** [comment]
Sorry to hear you had such a rough time @DantonCorbel. You may seek some reprieve to know that also happens to me sometimes, but as you get more experienced you'll get a lot faster at identifying and fixing these "sporadic" issues, so hang in there!
